spring:
  application:
      name: GatewayService
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]': # Apply CORS to all routes
            allowedOrigins: "http://localhost:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
            allowedHeaders: "*"
            allowCredentials: true
      routes:
        - id: userservice
          predicates:
            - Path=/user/**
          uri: http://localhost:8080/
          filters:
            - CustomFilter

        - id: curdservice
          uri: http://localhost:8112/
          predicates:
            - Path=/rest/**
          filters:
           - CustomFilter

server:
  port : 8111

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/


